"""rich_text_posts

Revision ID: 67f2e20e9b75
Revises: f2894b607a41
Create Date: 2016-02-24 16:18:05.482000

"""

# revision identifiers, used by Alembic.
revision = '67f2e20e9b75'
down_revision = 'f2894b607a41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
