"""initial migration

Revision ID: c9b9a90d996f
Revises: None
Create Date: 2016-02-21 20:23:24.764000

"""

# revision identifiers, used by Alembic.
revision = 'c9b9a90d996f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
