"""caching of vatar hashes

Revision ID: e38e661e5e17
Revises: 9183c2d071f0
Create Date: 2016-02-23 21:15:52.079000

"""

# revision identifiers, used by Alembic.
revision = 'e38e661e5e17'
down_revision = '9183c2d071f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
